dict_one = {0: 100, 1: 444, 2: 647, 3: 363}

# lets print fourth key from dict_one dictionary that does not exist
print(dict_one[4])  # error message appears: "KeyError: 4"
